# Generated by Django 3.1.7 on 2021-02-19 19:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Main Category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_text', tinymce.models.HTMLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='news.Category')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.maincategory')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
